apiVersion: v1
kind: Secret
metadata:
  name: {{ include "certctl.fullname" . }}-postgres
  labels:
    {{- include "certctl.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
type: Opaque
stringData:
  password: {{ .Values.postgresql.auth.password | default "changeme" | quote }}
  username: {{ .Values.postgresql.auth.username | quote }}
  database: {{ .Values.postgresql.auth.database | quote }}
