apiVersion: v1
kind: Secret
metadata:
  name: {{ include "certctl.fullname" . }}-postgres
  labels:
    {{- include "certctl.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
type: Opaque
stringData:
  {{- if not .Values.postgresql.auth.password }}
  {{- fail "postgresql.auth.password is required" }}
  {{- end }}
  password: {{ .Values.postgresql.auth.password | quote }}
  username: {{ .Values.postgresql.auth.username | quote }}
  database: {{ .Values.postgresql.auth.database | quote }}
